# fly.toml app configuration file generated for bicirio-backend on 2023-09-05T14:01:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bicirio-backend"
primary_region = "bog"

[http_service]
  internal_port = 3005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
