# fly.toml app configuration file generated for bicirio-backend on 2023-06-21T00:16:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bicirio-backend"
primary_region = "bog"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 3005

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
